version: "3.9"
services:
  islash-playground:
    container_name: islash-playground-container
    build:
      context: .
      dockerfile: ./Dockerfile.playground
    volumes:
      - type: bind
        source: ./example-programs
        target: /home/islash-playground/example-programs
