on:
  pull_request:
    types:
      - "opened"
      - "reopened"
    branches:
      - "main"
jobs:
  test-isl-programs:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: "Run Shell Script"
        run: ls
    