on:  
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Test-ISlash-Programs:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"
      - name: "Setup Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.19"
      - name: "Build ISlash Executable"
        run: "go build"
      - name: "Run ISlash Programs"
        run: "bash ./.github/workflows/run-islash-programs.sh"
