on:  
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  environment-setup:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"
      - name: "Setup Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.19"
      - name: "Build ISlash Executable"
        run: "go build"

  build-matrix:
    needs: "environment-setup"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Build Matrix"
        run: |
          echo '::set-output name=version_matrix::["12","14","16"]'
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}

  matrix:
    needs: "build-matrix"
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    steps:
      - name: "Test Matrix"
        run: echo ${{ matrix.version }}
