on:  
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Environment-Setup:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"
      - name: "Setup Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.19"
      - name: "Build ISlash Executable"
        run: "go build"

  Build-Matrix:
    needs: "Environment-Setup"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Build Matrix"
        id: "build-matrix"
        run: |
          echo '::set-output name=version_matrix::["12","14","16"]'
          bash .github/workflows/get-programs-list.sh
    outputs:
      version-matrix: ${{ steps.build-matrix.outputs.version-matrix }}

  Test-Matrix:
    needs: "Build-Matrix"
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.version-matrix) }}
    steps:
      - name: "Test Matrix"
        run: echo ${{ matrix.version }}
